using System.Text;
using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;

namespace Hackcom.Dapper
{
    public interface IRepoContext
    {
        IDbConnection CeateConnection();
    }

    public interface IDapperRepository<T>
    {
        string SelectFields { get; }
        string TableName { get; }

        IEnumerable<T> GetAll();
        T Get(object primaryKey);
        IEnumerable<T> Find(string where, object param = null);
        IEnumerable<T> Select(string extraQuery, object param = null);
        IEnumerable<T> Join<T1>(IDapperRepository<T1> join1, Func<T, T1, T> map, string joinOn, string where = null, string joinHint = null);
        IEnumerable<T> Join<T1, T2>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, Func<T, T1, T2, T> map, string joinOn, string where = null, string joinHint = null);
        IEnumerable<T> Join<T1, T2, T3>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, Func<T, T1, T2, T3, T> map, string joinOn, string where = null, string joinHint = null);
        IEnumerable<T> Join<T1, T2, T3, T4>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, IDapperRepository<T4> join4, Func<T, T1, T2, T3, T4, T> map, string joinOn, string where = null, string joinHint = null);
        IEnumerable<T> Join<T1, T2, T3, T4, T5>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, IDapperRepository<T4> join4, IDapperRepository<T5> join5, Func<T, T1, T2, T3, T4, T5, T> map, string joinOn, string where = null, string joinHint = null);
        IEnumerable<T> Join<T1, T2, T3, T4, T5, T6>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, IDapperRepository<T4> join4, IDapperRepository<T5> join5, IDapperRepository<T6> join6, Func<T, T1, T2, T3, T4, T5, T6, T> map, string joinOn, string where = null, string joinHint = null);

        int Insert(T entity);
        T Add(T item);
        T Update(T item);
        int Remove(object primaryKey);
        int Execute(string sql, object param);

        void Set(string tableName = null, string querySelect = null, string queryInsert = null, string queryUpdate = null, string queryPrimaryKey = null, bool primaryKeyAutoGenerated = true);
        void MapFields(string[] dbColumns, string[] entityProperties = null);
        string GetEntityFieldName(string dbFieldName);
    }

    public class DapperRepository<T> : IDapperRepository<T>
    {
        #region Properties
        private IRepoContext _ctx;

        private string _tableName;
        public string TableName
        {
            get
            {
                if (string.IsNullOrEmpty(_tableName))
                {
                    _tableName = typeof(T).Name;
                }

                return _tableName;
            }
            set
            {
                _tableName = value;
            }
        }

        private string _selectFields;
        public string SelectFields
        {
            get
            {
                if (string.IsNullOrEmpty(_selectFields))
                {
                    if (EntityFields.Any())
                    {
                        var fields = EntityFields.TakeWhile((t, i) => DbFields.Count >= i).Select((t, i) => string.Format("{0}.{1} AS {2}", TableName, DbFields[i], t)).ToList();
                        _selectFields = Concat(fields);
                    }
                    else
                    {
                        _selectFields = Concat(DbFields);
                    }
                }
                return _selectFields;
            }
            set { _selectFields = value; }
        }

        private string _querySelect;
        protected string QuerySelect
        {
            get
            {
                if (string.IsNullOrEmpty(_querySelect))
                {
                    _querySelect = string.Format("Select {1} From {0}", TableName, SelectFields);
                }

                return _querySelect;
            }
            set
            {
                _querySelect = value;
            }
        }

        private string _queryPrimaryKey;
        protected string QueryPrimaryKey
        {
            get
            {
                if (string.IsNullOrEmpty(_queryPrimaryKey))
                {
                    _queryPrimaryKey = FirstField+"=@"+EntityFields[0];
                }

                return _queryPrimaryKey;
            }
            set
            {
                _queryPrimaryKey = value;
            }
        } 

        private string _queryInsert;
        protected string QueryInsert
        {
            get
            {
                if(string.IsNullOrEmpty(_queryInsert))
                {
                    List<string> dbFields;
                    List<string> entityFields;

                    if (IsPrimaryKeyAutoGenerated)
                    {
                        dbFields = DbFields.Skip(1).ToList();
                        entityFields = EntityFields.Skip(1).ToList();
                    }
                    else
                    {
                        dbFields = DbFields;
                        entityFields = EntityFields;
                    }

                    _queryInsert = string.Format("Insert Into {0}({1}) Values(@{2})", 
                        TableName,
                        Concat(dbFields), 
                        Concat(entityFields, ",@"));
                }
                return _queryInsert;
            }
            set
            {
                _queryInsert = value;
            }
        }

        private string _queryUpdate;
        protected string QueryUpdate
        {
            get
            {
                if (string.IsNullOrEmpty(_queryUpdate))
                {
                    var placeHolder = "{{value}}";
                    var setFields = DbFields.Select(c => c + "=@" + placeHolder).ToList();

                    for (int i = 0; i < setFields.Count; ++i)
                    {
                        if (i >= EntityFields.Count)
                        {
                            break;
                        }

                        setFields[i] = setFields[i].Replace(placeHolder, EntityFields[i]);
                    }

                    _queryUpdate = string.Format("Update {0} Set {1} Where {2}",
                        TableName,
                        Concat(setFields.Skip(1).Select(f => f)),
                        QueryPrimaryKey);
                }

                return _queryUpdate;
            }
            set
            {
                _queryUpdate = value;
            }
        }

        private List<string> _dbFields;
        protected List<string> DbFields
        {
            get 
            {
                if (_dbFields == null)
                {
                    _dbFields = new List<string>(GetEntityFieldNames());
                }
                return _dbFields;
            }
            set
            {
                _dbFields = value;
            }
        }

        protected string FirstField
        {
            get
            { 
                return DbFields[0];
            }
        }

        private List<string> _entityFields;
        protected List<string> EntityFields
        {
            get {
                if (_entityFields == null)
                {
                    _entityFields = new List<string>(GetEntityFieldNames());
                }
                return _entityFields;
            }

            set
            {
                _entityFields = value;
            }
        }

        private bool _isPrimaryKeyAutoGenerated = true;
        protected bool IsPrimaryKeyAutoGenerated
        {
            get { return _isPrimaryKeyAutoGenerated; }
            set { _isPrimaryKeyAutoGenerated = value; }
        }

        #endregion

        #region Public Interfaces
        public DapperRepository(IRepoContext ctx)
        {
            _ctx = ctx;
        }

        public void Set(string tableName=null, string querySelect = null, string queryInsert = null, string queryUpdate = null, string queryPrimaryKey=null, bool primaryKeyAutoGenerated = true) 
        {
            TableName = tableName;
            QuerySelect = querySelect;
            QueryInsert = queryInsert;
            QueryUpdate = queryUpdate;
            QueryPrimaryKey = queryPrimaryKey;
            IsPrimaryKeyAutoGenerated = primaryKeyAutoGenerated;
        }

        public void MapFields(string[] dbColumns, string[] entityProperties = null)
        {
            if (dbColumns == null || dbColumns.Any() == false)
            {
                throw new Exception("No property defined");
            }

            DbFields = new List<string>(dbColumns);
            if (entityProperties != null)
            {
                EntityFields = new List<string>(entityProperties);
            }
        }

        public virtual IEnumerable<T> GetAll()
        {
            return UsingDb(db => db.Query<T>(QuerySelect, null));
        }

        public virtual T Get(object primaryKey)
        {
            return Find(QueryPrimaryKey, primaryKey).FirstOrDefault();
        }

        public virtual IEnumerable<T> Find(string where, object param = null)
        {
            string sql = SelectWhere(where);
            return UsingDb(db => db.Query<T>(sql, param));
        }

        public virtual IEnumerable<T> Select(string extraQuery, object param = null)
        {
            string sql = string.Format("{0} {1}", QuerySelect, extraQuery);
            return UsingDb(db => db.Query<T>(sql, param));
        }

        public virtual IEnumerable<T> Join<T1>(IDapperRepository<T1> join1, Func<T, T1, T> map, string joinOn, string where = null, string joinHint = null)
        {
            var joinSelectFields = new List<string>()
            {
                SelectFields,
                join1.SelectFields
            };
            var joinTableNames = new List<string>()
            {
                join1.TableName
            };
            var sql = GetJoinQuery(joinOn, where, joinSelectFields, joinTableNames, joinHint);

            var fields = GetJoinOnRightFields(joinOn).ToArray();
            var i = 0;
            var splitOn = new List<string>()
            {
                join1.GetEntityFieldName(fields[i++])
            };

            return UsingDb(db => db.Query(sql, map, splitOn: Concat(splitOn)));
        }

        public virtual IEnumerable<T> Join<T1, T2>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, Func<T, T1, T2, T> map, string joinOn, string where = null, string joinHint = null)
        {
            var joinSelectFields = new List<string>()
            {
                SelectFields,
                join1.SelectFields,
                join2.SelectFields
            };
            var joinTableNames = new List<string>()
            {
                join1.TableName,
                join2.TableName
            };
            var sql = GetJoinQuery(joinOn, where, joinSelectFields, joinTableNames, joinHint);

            var joinFields = GetJoinOnRightFields(joinOn).ToArray();
            var i = 0;
            var splitOn = new List<string>
            {
                join1.GetEntityFieldName(joinFields[i++]),
                join2.GetEntityFieldName(joinFields[i++])
            };

            return UsingDb(db => db.Query(sql, map, splitOn: Concat(splitOn)));
        }

        public virtual IEnumerable<T> Join<T1, T2, T3>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, Func<T, T1, T2, T3, T> map, string joinOn, string where = null, string joinHint = null)
        {
            var joinSelectFields = new List<string>()
            {
                SelectFields,
                join1.SelectFields,
                join2.SelectFields,
                join3.SelectFields
            };
            var joinTableNames = new List<string>()
            {
                join1.TableName,
                join2.TableName,
                join3.TableName
            };
            var sql = GetJoinQuery(joinOn, where, joinSelectFields, joinTableNames, joinHint);

            var joinFields = GetJoinOnRightFields(joinOn).ToArray();
            var i = 0;
            var splitOn = new List<string>
            {
                join1.GetEntityFieldName(joinFields[i++]),
                join2.GetEntityFieldName(joinFields[i++]),
                join3.GetEntityFieldName(joinFields[i++])
            };

            return UsingDb(db => db.Query(sql, map, splitOn: Concat(splitOn)));
            
        }

        public virtual IEnumerable<T> Join<T1, T2, T3, T4>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, IDapperRepository<T4> join4, Func<T, T1, T2, T3, T4, T> map, string joinOn, string where = null, string joinHint = null)
        {
            var joinSelectFields = new List<string>()
            {
                SelectFields,
                join1.SelectFields,
                join2.SelectFields,
                join3.SelectFields,
                join4.SelectFields
            };
            var joinTableNames = new List<string>()
            {
                join1.TableName,
                join2.TableName,
                join3.TableName,
                join4.TableName
            };
            var sql = GetJoinQuery(joinOn, where, joinSelectFields, joinTableNames, joinHint);

            var joinFields = GetJoinOnRightFields(joinOn).ToArray();
            var i = 0;
            var splitOn = new List<string>
            {
                join1.GetEntityFieldName(joinFields[i++]),
                join2.GetEntityFieldName(joinFields[i++]),
                join3.GetEntityFieldName(joinFields[i++]),
                join4.GetEntityFieldName(joinFields[i++])
            };

            return UsingDb(db => db.Query(sql, map, splitOn: Concat(splitOn)));
        }

        public virtual IEnumerable<T> Join<T1, T2, T3, T4, T5>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, IDapperRepository<T4> join4, IDapperRepository<T5> join5, Func<T, T1, T2, T3, T4, T5, T> map, string joinOn, string where = null, string joinHint = null)
        {
            var joinSelectFields = new List<string>()
            {
                SelectFields,
                join1.SelectFields,
                join2.SelectFields,
                join3.SelectFields,
                join4.SelectFields,
                join5.SelectFields
            };
            var joinTableNames = new List<string>()
            {
                join1.TableName,
                join2.TableName,
                join3.TableName,
                join4.TableName,
                join5.TableName
            };
            var sql = GetJoinQuery(joinOn, where, joinSelectFields, joinTableNames, joinHint);

            var joinFields = GetJoinOnRightFields(joinOn).ToArray();
            var i = 0;
            var splitOn = new List<string>
            {
                join1.GetEntityFieldName(joinFields[i++]),
                join2.GetEntityFieldName(joinFields[i++]),
                join3.GetEntityFieldName(joinFields[i++]),
                join4.GetEntityFieldName(joinFields[i++]),
                join5.GetEntityFieldName(joinFields[i++])
            };

            return UsingDb(db => db.Query(sql, map, splitOn: Concat(splitOn)));
        }
        
        public virtual IEnumerable<T> Join<T1, T2, T3, T4, T5, T6>(IDapperRepository<T1> join1, IDapperRepository<T2> join2, IDapperRepository<T3> join3, IDapperRepository<T4> join4, IDapperRepository<T5> join5, IDapperRepository<T6> join6, Func<T, T1, T2, T3, T4, T5, T6, T> map, string joinOn, string where = null, string joinHint = null)
        {
            var joinSelectFields = new List<string>()
            {
                SelectFields,
                join1.SelectFields,
                join2.SelectFields,
                join3.SelectFields,
                join4.SelectFields,
                join5.SelectFields,
                join6.SelectFields
            };
            var joinTableNames = new List<string>()
            {
                join1.TableName,
                join2.TableName,
                join3.TableName,
                join4.TableName,
                join5.TableName,
                join6.TableName
            };
            var sql = GetJoinQuery(joinOn, where, joinSelectFields, joinTableNames);

            var joinFields = GetJoinOnRightFields(joinOn).ToArray();
            var i = 0;
            var splitOn = new List<string>
            {
                join1.GetEntityFieldName(joinFields[i++]),
                join2.GetEntityFieldName(joinFields[i++]),
                join3.GetEntityFieldName(joinFields[i++]),
                join4.GetEntityFieldName(joinFields[i++]),
                join5.GetEntityFieldName(joinFields[i++]),
                join6.GetEntityFieldName(joinFields[i++])
            };

            return UsingDb(db => db.Query(sql, map, splitOn: Concat(splitOn)));
        }

        public virtual T Add(T entity)
        {
            string where = IsPrimaryKeyAutoGenerated
                ? string.Format("{0} = SCOPE_IDENTITY()", FirstField)
                : QueryPrimaryKey;
            string sql = string.Format("{0}; {1}", QueryInsert, SelectWhere(where));
            
            var param = Mapping(entity) as object;
            return UsingDb(db => db.Query<T>(sql, param)).First();
        }

        public virtual int Insert(T entity)
        {
            string sql = string.Format("{0}", QueryInsert);
            var param = Mapping(entity) as object;
            return UsingDb(db => db.Execute(sql, param));
        }

        public virtual T Update(T entity)
        {
            var param = Mapping(entity) as object;
            UsingDb(db => db.Execute(QueryUpdate, param));
            return entity;
        }

        public virtual int Remove(object primaryKey)
        {
            string sql = string.Format("Delete {0} Where {1}", TableName, QueryPrimaryKey);
            return UsingDb(db => db.Execute(sql, primaryKey));
        }

        public virtual int Execute(string sql, object param)
        {
            return UsingDb(db => db.Execute(sql, param));
        }

        public string GetEntityFieldName(string dbFieldName)
        {
            var index = DbFields.FindIndex(f => String.Compare(f, dbFieldName, StringComparison.OrdinalIgnoreCase) == 0);
            return (index >= 0 && EntityFields.Count > index) ? EntityFields.ElementAt(index) : dbFieldName;
        }

        #endregion

        #region Protected Interfaces
        protected U UsingDb<U>(Func<IDbConnection, U> func)
        {
            using (var db = _ctx.CeateConnection())
            {
                return func(db);
            }
        }

        protected virtual string SelectWhere(string where)
        {
            return string.Format("{0} Where {1}", QuerySelect, where);
        }

        protected virtual T Mapping(T entity)
        {
            return entity;
        }
        #endregion

        #region Private Functions
        private IEnumerable<string> GetEntityFieldNames()
        {
            return GetEntityFieldNames<T>();
        }

        private IEnumerable<string> GetEntityFieldNames<TOther>()
        {
            PropertyInfo[] props = typeof(TOther).GetProperties();
            return props.Where(p => !p.GetGetMethod().IsVirtual).Select(p => p.Name);
        }

        private IEnumerable<string> GetJoinOn(string joinOn)
        {
            return joinOn.Split(',').Select(j => j.Trim());
        }

        private IEnumerable<string> GetJoinOnRightFields(string joinOn)
        {
            var splitOns = GetJoinOn(joinOn)
                .Where(j => j.Contains('='))
                .Select(j => j.Substring(j.LastIndexOf('.') + 1).Trim());
            return splitOns;
        }

        private string GetJoinQuery(string joinOn, string where, List<string> joinSelectFields, List<string> joinTableNames, string joinHint = null)
        {
            var joinOns = GetJoinOn(joinOn).ToArray();

            if (joinTableNames.Count != joinOns.Count())
            {
                throw new Exception("Table number and join number does not match.");
            }

            var joinHints = joinHint == null ? new List<string>() : joinHint.Split(',').ToList();

            var fields = Concat(joinSelectFields);
            var sql = new StringBuilder();
            sql.AppendFormat("SELECT {0} FROM {1}", fields, TableName);
            for (var i = 0; i < joinTableNames.Count; ++i)
            {
                var table = joinTableNames[i];
                var joinQuery = joinOns[i];
                var innerOuter = joinHints.Count > i ? joinHints[i] : "INNER";

                sql.AppendFormat(" {0} JOIN {1} ON {2}", innerOuter, table, joinQuery);
            }
            if (!string.IsNullOrEmpty(where))
            {
                sql.AppendFormat(" WHERE {0}", where);
            }
            return sql.ToString();
        }

        private string Concat(IEnumerable<string> arr, string separator = ",")
        {
            return arr.Aggregate((x, y) => x + separator + y);
        }

        #endregion
    }
}
